[project]
name = "mdpy"
version = "0.1.0"
description = "Simple markdown viewer made with PySide6"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown2>=2.5.3",
    "pygments>=2.19.2",
    "pyside6>=6.9.1",
]
